---
version: "2.0"

# TODO: Add prom scraping

services:
  penumbra:
    image: samangan/penumbra:v10
    env:
      - S3_KEY={s3_key}
      - S3_SECRET={s3_secret}
      - KEY_PATH={config_bucket}
      - FILE_NAME={config_tar_file}
      - PD_HOST=localhost:26658
      - ID=0
      - LOG=-tendermint.log
    expose:
      - port: 26656
        to: 
          - global: true
      - port: 26657
        to: 
         - global: true
profiles:
  compute:
    penumbra:
      resources:
        cpu:
          units: 4
        memory:
          size: 4Gi
        storage:
          size: 75Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        penumbra:
          denom: uakt
          amount: 500
deployment:
  penumbra:
    akash:
      profile: penumbra
      count: 1
